/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ScrapeData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ScrapePage": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ScrapeQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "TriggerScrape": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}